### ISSUE TITLE
Auto limit GPU after certain time

### ISSUE THREAD

**Issue by SouljaVR** [Raphiiko/Oyasumi#1]
Hi - This is a really awesome project. I've wanted something like this for a while and i'm glad someone with the right experience is working on it. Thank you for your contributions!

I think GPU limiting functionality would be really beneficial. It would save a lot of energy consumption when asleep since most peoples GPU's are running at almost full load while sleeping in VRC. Its unnefficient and has other downsides like increased heat and worst case scenario, lower hardware life span. There is another tool that is able to do this, but it isnt in English which makes it difficult to use for me and others:

https://github.com/njm2360/VRChatGPUTool

Also being able to auto limit the game resolution when sleeping would be great, but I'm not sure if its even possible to override SteamVR's resolution with an external app. Worth mentioning but I understand if it cant be done. 

I hope you consider this, thank you once again :)

**Comment by Raphiiko** [comment]
That's actually a fantastic idea, something I didn't know I wanted! I'll have a look at what's possible. 

I'm not sure if there is a public API available for adjusting SteamVR's render resolution preference. OVRAS seems to allow [adjusting super sampling](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings), but, a. I'm not entirely sure if this is the exact same thing, and b. it seems to require a restart of SteamVR/OpenVR, which isn't very ideal considering the user is likely to be asleep. 

At the very least it should be possible to automatically adjust the power limit of Nvidia GPU's, I'll have a look if I can do the same for AMD cards.

**Comment by Raphiiko** [comment]
I cannot seem to find a way to do this for AMD cards on Windows. For Nvidia cards it's quite straight forward, but the only resources I find for AMD, be it ways to interact with the driver, or command line tools, all seem to be on Linux only. 
From the quick look I had at the source of the Japanese tool you linked, the only ways it has to interact with a GPU is through Nvidia SMI, so I'm guessing no AMD support there either. 

I'll be trying to add this functionality to Oyasumi, but for now it will be limited to Nvidia cards only. If you or anyone else has an idea on how to adjust power limits for AMD cards programatically on Windows (be it through a command line tool or some API), I'd really appreciate some help.

**Comment by SouljaVR** [comment]
Sorry for the late reply to this, didn't realise I got a response back from you - I'm glad you liked the idea! And even more glad to see you giving implementation a shot, thank you so much Raphiiko!

I personally haven't seen any tools that can limit power on AMD cards either so I think its a no go unfortunately. Sorry I can't be of more help there. But even if its just an Nvidia thing only, works with me and most other VR players. I'd love to see that implemented in this :)

Thanks again!

**Comment by Raphiiko** [comment]
A Nvidia implementation has been added. It will be released shortly in `v0.3.0` ^^

AMD support will remain to be tracked in #7. 

Closing

**Comment by SouljaVR** [comment]
Sorry for the late response to this - I appreciate you getting this added so much! Gave it a try when I went to sleep yesterday and it works perfectly. Thank you!
