### ISSUE TITLE
Toggle for OSC

### ISSUE THREAD

**Issue by ZenithVal** [Raphiiko/Oyasumi#18]
There should be a clear on or off switch for Oyasumi's OSC features. I personally do not use any Oyasumi OSC integration but learned the app occupies ports regardless. 

I didn't remember or assume OSC from this app was on by default and was confused why another app was spitting errors at me until I remembered Oyasumi had OSC integration. Searched Oyasumi an option to disable OSC to no avail; Instead I just set the ports it uses way out of range of my other apps.

**Comment by Raphiiko** [comment]
An incoming port for OSC is bound by default for the included [Expression Menu](https://github.com/Raphiiko/Oyasumi/wiki/Oyasumi-Expression-Menu). Afaik this is currently the only functionality that uses incoming OSC packets, so I think I can add an option to disable support for the menu. As long as that is disabled, there is no need for the incoming port to be bound.

**Comment by Raphiiko** [comment]
This has been added in https://github.com/Raphiiko/Oyasumi/commit/df515ea5905dc3e2ffcd5e670445ae1166b19c68! It will be included in the next release.

![image](https://github.com/Raphiiko/Oyasumi/assets/111654848/081c899e-fb8f-4f54-9a06-677b11ad7644)
