### ISSUE TITLE
OSC Automation Data Type Suggestion

### ISSUE THREAD

**Issue by aabbey-stack** [Raphiiko/Oyasumi#25]
Hello, 
I really like the OSC automation tab, but I feel like Chatbox OSC integration would be used more frequently than the other types. For example when "Oyasumi detects you are asleep based on your movement" or when "At specific time", more tech savvy users could make a Chatbox OSC automation that will display for how long they've been asleep for or/with any other custom text (maybe expose more variables to the user, since I assume it keeps track for how long your "sleep mode" is activated for). 

Here's some resources around how to call Chatbox OSC address that I've found: 
[VRChat change-logs mentioning variables for the endpoints](https://docs.vrchat.com/docs/vrchat-202222p3)
[very simple OSC Chatbox application & easy to understand](https://github.com/I5UCC/VRCTextboxOSC)

At last here's some simple graphical preview, that I made in Photoshop at how such feature could look like:
![Oyasumi_Up5yfIGLDv](https://github.com/Raphiiko/Oyasumi/assets/61197745/a52a3f41-b1ac-4369-9720-eb5ef664e602)

_Let me know your thoughts on this! I find this project really interesting not just from sleeping in VR pov._

**Comment by Raphiiko** [comment]
Hey! The OSC scripting does indeed come with some limitations: 

- It doesn't support sending multiple values in a single payload (Like vrchat's chatbox addresses need)
- It doesn't support any other data types than float/bool/int, (like string, which would also be needed for the chatbox)

Its initial purpose was only really to control avatar parameters for the sleeping animations feature, and to give users the option to add support for their own locomotion prefabs or avatar animations. Simple to use for beginners, but flexible enough to allow people to do custom stuff if they really wanted to. 

I'd love to expand its capabilities some day, but the sad reality of it is that it's currently not a very high priority for me. (There's so many things I still want to do) 

Tthe scripting syntax would have to be expanded to support this, as well as the simple scripting view to support each new addition, which sadly aren't very trivial tasks. I hope to at some point at least get those two pain points I mentioned out of the way. The kind of templating you're describing is probably a lot further away, but I could see it being a really cool feature. If you or anyone you know is able to help out, I'd appreciate all the help!

If that templating (Chatbox that shows time asleep) is something you want to do right now though, It's something you could script:

Assuming you can script something that sits in between Oyasumi and VRChat, you can send `1` to `/avatar/parameters/Oyasumi/Cmd`, and Oyasumi will reply with a boolean value on `/avatar/parameters/Oyasumi/SleepMode`. If you send this once and then keep an eye on values coming from that last address, you can figure out when the sleep mode was enabled. From there, you can figure out how long you've been asleep and send the chatbox osc messages yourself.
Here's some more info about interacting with Oyasumi over OSC: https://github.com/Raphiiko/Oyasumi/wiki/Controlling-Oyasumi-over-OSC#commands

**Comment by Raphiiko** [comment]
For now I'm closing this in favour of #26.
