### ISSUE TITLE
Add initial support for Korean 

### ISSUE THREAD

**Issue by Raphiiko** [Raphiiko/Oyasumi#3]
To make this application accessible for even more people, I would really like to add Korean translations.

If you speak both English and Korean and you would like to help out, I would really appreciate it!

Please read the wiki page on adding translations for instructions on how to get started: https://github.com/Raphiiko/Oyasumi/wiki/Adding-Translations

**Comment by soumt-r** [comment]
[ko.zip](https://github.com/Raphiiko/Oyasumi/files/10020034/ko.zip)
Hi, Raphiiko.

My English isn't that good, but I tried to translate it into Korean.
I hope it was helpful.

**Comment by Raphiiko** [comment]
Hey, thank you so much for helping out! 
I'll try to release a development build with your translations after I get back from work today. 
Do you want me to credit you as "Soumt" or as "soumt-r"?

**Comment by soumt-r** [comment]
I want "Soumt"! Thanks!

**Comment by Raphiiko** [comment]
Alright, I've added your translations here: https://github.com/Raphiiko/Oyasumi/commit/de676de5e47e16e3bf39d8164c3293e4482c6be0
Everything should now be in the latest development build: https://github.com/Raphiiko/Oyasumi/releases/tag/oyasumi-vDEV

Could you please let me know if everything looks alright? It mostly looks ok to me, but especially regarding things like linebreaks, I can't really tell if it's all ok without knowing any Korean.

If everything turns out to be ok, I'll include this with the next update ^^

**Comment by soumt-r** [comment]
I see some unintended linesbreaks, but I don't think it's a big problem to read as a Korean.
But I found a translation mistake...
Please change belowLimit-title to "상한 미만" and atLimitOrAbove-title to "상한 이상"

Other than that, there seems to be no big problem.
I will contact you if I find a problem later.

**Comment by Raphiiko** [comment]
Ok sweet, I've updated those translations. Thanks for the double check!
I'll include this with the next update, which will probably come when I finish the current feature I'm working on. 
I'll close this issue for now, but if you find anything else feel free to reopen it, or just send me a message on Discord!
