### ISSUE TITLE
Toggle Sleep State using OSC

### ISSUE THREAD

**Issue by Okabintaro** [Raphiiko/Oyasumi#9]
I think it would be a nice feature if you could enable and disable sleep mode using a bool parameter and OSC.
That would make it possible to add a toggle to the expression menu or use a contact or something on the avatar without having to resort to overlays to show the desktop and the application.

**Comment by Raphiiko** [comment]
Ahh yes! Something like that has been playing in my mind as well. 

I'm considering a unity package with a menu and some parameters that can control some of the basic functionality. 
For example, I've been finding myself really wanting an in-game toggle for the upcoming sleeping animation automations, so I feel like toggling the sleep mode could fit right in. 

Currently I've got some other things queue'd up, but it is something I would like to add eventually.

**Comment by Raphiiko** [comment]
@Okabintaro I've added this feature and it's currently in develop. It'll come with the next release, which will hopefully be somewhere next week. If you want to try it out before then, you can do so with the latest [Development Build](https://github.com/Raphiiko/Oyasumi/releases/tag/oyasumi-vDEV).

If you want to build something yourself, you can find documentation on how to control Oyasumi over OSC [here](https://github.com/Raphiiko/Oyasumi/wiki/Controlling-Oyasumi-over-OSC). 

Alternatively, there is now a premade unity asset that you can use instead. You can find instructions for how to add this to your avatar [here](https://github.com/Raphiiko/Oyasumi/wiki/Oyasumi-Expression-Menu).

![ApplicationFrameHost_3sg15YpRnA](https://user-images.githubusercontent.com/111654848/198674872-b90a7ebc-95ef-4dc5-b9b3-8c4537b80169.png)
